# Generated by Django 5.2.1 on 2025-05-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=100)),
                ('colony', models.CharField(max_length=100)),
                ('last_donation_date', models.DateField()),
                ('is_profile_public', models.BooleanField(default=False)),
                ('is_healthy', models.BooleanField(default=True)),
                ('total_donations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('required_blood_group', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=100)),
                ('colony', models.CharField(max_length=100)),
                ('urgency_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=20)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.donor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patientrequest')),
            ],
        ),
    ]
