# Generated by Django 5.2.1 on 2025-05-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='cnic',
            field=models.CharField(default='0000000000000', max_length=13),
        ),
        migrations.AddField(
            model_name='donor',
            name='full_address',
            field=models.TextField(default='Not provided'),
        ),
        migrations.AddField(
            model_name='donor',
            name='gender',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='donor',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='case_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='cnic',
            field=models.CharField(default='0000000000000', max_length=13),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='gender',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='hospital_address',
            field=models.TextField(default='Not provided'),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='hospital_name',
            field=models.CharField(default='Unknown Hospital', max_length=255),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='phone',
            field=models.CharField(default='03000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='units_needed',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='colony',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='patient_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='required_blood_group',
            field=models.CharField(default='O+', max_length=5),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='urgency_level',
            field=models.CharField(default='Normal', max_length=20),
        ),
    ]
