# Generated by Django 5.2.1 on 2025-05-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donor_cnic_donor_full_address_donor_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailresponse',
            name='response_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available'), ('Email Sent', 'Email Sent')], max_length=20),
        ),
    ]
