# Generated by Django 5.2 on 2025-05-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_emailresponse_response_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrequest',
            name='fulfilled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
