# Generated by Django 5.2.1 on 2025-05-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_patientrequest_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='patientrequest',
            name='fulfilled_at',
        ),
        migrations.RemoveField(
            model_name='patientrequest',
            name='submitted_at',
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
