# Generated by Django 5.2.1 on 2025-05-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_patientrequest_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrequest',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='verification_code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
