# Generated by Django 5.2.1 on 2025-05-28 12:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_patientrequest_fulfilled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrequest',
            name='verification_code',
            field=models.CharField(default=core.models.generate_code, max_length=6),
        ),
    ]
