# Generated by Django 5.2.1 on 2025-05-28 14:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_patientrequest_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrequest',
            name='verification_code',
            field=models.CharField(default=core.models.generate_code, editable=False, max_length=6),
        ),
    ]
