# Generated by Django 5.2.1 on 2025-05-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_patientrequest_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrequest',
            name='fulfilled_at',
        ),
        migrations.AddField(
            model_name='donor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailresponse',
            name='response_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available'), ('Email Sent', 'Email Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=20),
        ),
    ]
