# Generated by Django 5.2.1 on 2025-05-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_patientrequest_fulfilled_at_donor_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrequest',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
