# Generated by Django 5.2 on 2025-05-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_patientrequest_latitude_patientrequest_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
