# Generated by Django 5.2 on 2025-05-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_patientrequest_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrequest',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='patientrequest',
            name='longitude',
        ),
        migrations.AddField(
            model_name='donor',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
